language: csharp
solution: Melody.sln
mono: none
dotnet: 3.0.100
script:
  - dotnet restore
before_deploy:
  - tar -zcf Melody.tar.gz Melody
deploy:
  - provider: s3
    access_key_id: "AKIAZKY2NWBZVHEFUXG3"
    secret_access_key: &1
      secure: "lkwTxQpU3h2WvOUoFe3XvhUyzodJeSC3eZrLMf2h+oVUgbAffZLH17Mlyu1hboF+R67AUG7mIofPad0l4RIkXG7+bv6xHyhy616KJAKzjij1VNtwQ4nq/N+/Yy+s4Go4eloXcXxr7C0ZMT8Vts+Hnmiw1bfHybZiheGxSnRta0vcgsPCq9WYO4kt1vnJhnfkQrYJ+j31G4NZQ2wiEBnFKdIgbjFWJmNqkkI3gn4/N8zBpQGJiUL8twASbxhNXtU9HqT7dWOM+AllNvRLlHXp/e5oKgV4aW7swq/jHwvvQuazT+LVl+sgt3fR+ehg6aeju06FtzPfLE/Gil2hiTi3KkaOQuQa++gn4uEhEZcoXR41orDjCPgJ/HEoeURVx83D+Own5wqG242GFee7/cxJhU2rFDLs/232iH44lk9ewC3g7cMfGHIBy/WdIlPJc1pXbPoyxhxWDjPOgYeVNGunbNVmHLIVSdto5+GxMSv9CG09fnFv/UyiAq+1/XfnomqdKAcRr9wAuwXqj7WausRO8W0PRUaUAROo1M7i2KxYeiWODU84K8+wuwAKhTirb602Yv6V05kJoPm11Vuu/rruNi4BteaI7mMd0Lr2newHXt0UqYqNFsom9DwzCWqm7saQLsClErKXReFaImqg60Kzj/9QL7y7RvldFwG11CBJU1Y="
    on: &2
      branch: master
    bucket: melody
    skip_cleanup: true
    region: us-east-2
  - provider: codedeploy
    wait_until_deployed: true
    access_key_id: "AKIAZKY2NWBZVHEFUXG3"
    secret_access_key: *1
    bucket: melody
    key: Melody.tar.gz
    application: Melody
    bundle_type: tgz
    deployment_group: MelodyMusicGroup
    on: *2
    region: us-east-2
