version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu

hooks:
  ApplicationStop:
    - location: Shell_Scripts/Melody_serviceStop.sh
      timeout: 500
      runas: root
  ApplicationStart:
    - location: Shell_Scripts/Melody_serviceStart.sh
      timeout: 500
      runas: root